---
- name: "Install web "
  become: yes
  hosts: prod
  vars_files:
    - files/secrets/credentials.yml
  tasks:
    - name: "Install git"
      yum:
         name: git
         state: present
         update_cache: yes
    - name: "Clean Folder"
      file:
         path: /usr/share/nginx/html
         state: absent
    - name: "git clone to nginx folder"
      git:
         repo: https://github.com/diranetafen/static-website-example.git
         dest: /usr/share/nginx/html/
    - name: " Generate HTML "
      template:
         src: templates/index.html.j2
         dest: /usr/share/nginx/html/index.html
